[project]
name = "mcs"
version = "0.1.0"
description = "Global optimization by multilevel coordinate search (MCS)"
authors = [
    "Yannik Tausch <dev@ytausch.de>",
    "Varun Ojha <varun.ojha@ncl.ac.uk>",
    "Waltraud Huyer <huyer@cma.univie.ac.at",
    "Arnold Neumaier <neum@cma.univie.ac.at>"
]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."


[host-dependencies]
pip = "*"
setuptools = ">=70"
setuptools-scm = "*"

[dependencies]
python = ">=3.12.4"
numpy = ">=2.0.0,<2.1"
scipy = ">=1.13.1,<1.14"

[feature.development.dependencies]
pixi-pycharm = ">=0.0.5,<0.1"

[environments]
dev = { features = ["development"] }
